-- DropEnum
DROP TYPE "Role";

-- CreateTable
CREATE TABLE "BASE_CONFIGURATION" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BASE_CONFIGURATION_pkey" PRIMARY KEY ("id")
);
